[tool.poetry]
name = "hw-prod-ml-2"
version = "0.1.0"
description = ""
authors = ["mdchumakov <mdchumakov@avito.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
